### PR TITLE
Fix some errors: convert unicode to str, add pushing label before building project

### PR DESCRIPTION
**Pull request by jeet4320**
## What

1. `git_push_eb` is adds `!python/unicode`  to the yaml file and due to this AWS EB deployment fails
2. Add `Pushing` git label before building project, so that once users selects env from available env it should be booked.

# Testing

1. For first one, you need to have python version `2.7.10`, run `git_push_eb qa` and check uploaded application version zip file and open `env.yml` file (This issue was faced by Dianna and she tested it)
2. Run `git_push_eb qa`, it should add `Pushing` label before building project.

### CODE REVIEW

**Comment by whatisdot** [comment]
Need to update version.

**Comment by nickstanish** [comment]
Looks like this adds the label *after* the mfa check - seems like that the label should be added first

Also if the error fails (such as when docker isn't running) then the label is removed:

image

**Comment by jeet4320** [comment]
@nickstanish label should be added after MFA check, if user doesn't have access then there is no need to book env for that user.

Also, on exception like `docker is not running, docker build, deployment to EB` then `Pushing...` label will be removed by this code https://github.com/bodyshopbidsdotcom/git-scripts/pull/408/files#diff-cf66ab1114b91c1322d5cbcefc7fbcb7R140

**Comment by nickstanish** [comment]
I'm not sure that we should be removing pushing or the env label, but I get the reasoning behind it: the script isn't pushing anymore, and the changes aren't on the environment yet. But it also works as a reservation and the user is likely going to fix the issue (such as start docker) and run again, and it would be frustrating if someone else took the environment they were expecting in that time

**Comment by jeet4320** [comment]
If we leave env or pushing label on the PR then those labels would remain there if user decide not to deploy on that env. User can use other available envs if that env gets booked. If user is not getting any available env for long time and it is happening very often then we need to add more EB envs.

**Pull request merged**
